### ISSUE TITLE
bs4TabPanel tabName does not accept space

### ISSUE THREAD

**Issue by stephLH** [DivadNojnarg/bs4Dash#13]
I cannot set a tab name with space inside `bs4TabPanel `. 
The content of the second tab is not updated :
```
library(shiny)
library(bs4Dash)

shinyApp(
  ui = bs4DashPage(
    navbar = bs4DashNavbar(),
    sidebar = bs4DashSidebar(
      bs4SidebarMenuItem(
        "Tabs",
        tabName = "tabs"
      )
    ),
    body = bs4DashBody(
      bs4TabItems(
        bs4TabItem(
          tabName = "tabs",
          bs4TabCard(
            bs4TabPanel(
              tabName = "tab name 1",
              active = TRUE,
              "text 1"
            ),
            bs4TabPanel(
              tabName = "tab name 2",
              "text 2"
            )
          )
        )
      )
    )
  ),
  server = function(input, output) {}
)
```
But it works with a `tabPanel` in `shinydashboard` :
```
library(shiny)
library(shinydashboard)

shinyApp(
  ui = dashboardPage(
    header = dashboardHeader(),
    sidebar = bs4DashSidebar(
      sidebarMenu(
        menuSubItem(
          "Tabs",
          tabName = "tabs"
        )
      )
    ),
    body = dashboardBody(
      tabItems(
        tabItem(
          tabName = "tabs",
          tabBox(
            tabPanel(
              title = "tab name 1",
              "text 1"
            ),
            tabPanel(
              title = "tab name 2",
              "text 2"
            )
          )
        )
      )
    )
  ),
  server = function(input, output) {}
)
```

**Comment by DivadNojnarg** [comment]
Thanks for the report. 
Please download the latest level version:
`devtools:install_github(DivadNojnarg/bs4Dash)`
Below you will find a list of what is fixed. Let me know if you still have problems. If not, I will close ;)
# bs4Dash 0.3.0.9000
## Bug fix
- fix #8: Compatibility with shinyWidgets pickerInput. Thanks @pvictor.
- fix #13 in `bs4TabItem`: handle tabName with space. Thanks @stephLH.
- fix `bs4TabCard`: when the user set 2 or more tabs active at the same time, only 
the first one is selected

**Comment by stephLH** [comment]
Thank you! I just tested it.

Is it normal that tabName is trimmed when rendered in UI ?
`"tab name 1"` -> `"tabname1"`

Also, the character `/` within a tab name seems to cause the same initial problem.

**Comment by DivadNojnarg** [comment]
For each punctuation character actually . Try again and let me know
`devtools:install_github("DivadNojnarg/bs4Dash")`

**Comment by stephLH** [comment]
Perfect ;)
