### ISSUE TITLE
navbar dark skin causes sidebar toggle icons disappear ( only "light" works)

### ISSUE THREAD

**Issue by DivadNojnarg** [DivadNojnarg/bs4Dash#2]
```
library(shiny)
library(bs4Dash)
 
 shiny::shinyApp(
   ui = bs4DashPage(
     navbar = bs4DashNavbar(
      skin = "dark",
      rightUi = bs4DropdownMenu(
       show = TRUE,
       labelText = "!",
       status = "danger",
       src = "http://www.google.fr",
       bs4DropdownMenuItem(
        text = "message 1",
        date = "today"
       ),
       bs4DropdownMenuItem(
        text = "message 2",
        date = "yesterday"
       )
      )
     ),
     sidebar = bs4DashSidebar(),
     controlbar = bs4DashControlbar(),
     footer = bs4DashFooter(),
     title = "test",
     body = bs4DashBody()
   ),
   server = function(input, output) {}
 )
```

**Comment by federicomarini** [comment]
Probably related to this, David: I was looking for a way to change the fill of the icon in the control sidebar and for the sidebar menu (left). 
The snapshot at the time of the commit you reference had a `fill` argument. Is it still tweakable? I would like to avoid having this:

<img width="63" alt="image" src="https://user-images.githubusercontent.com/7447478/68594067-16f5c600-0497-11ea-9abc-092830fc689c.png">

**Comment by federicomarini** [comment]
(The screenshot is not so clear, but it is a piece of navbar on the left side)

**Comment by federicomarini** [comment]
Hi @DivadNojnarg ,
  
https://github.com/RinteRface/bs4Dash/blob/3b6e7a5a3b2e9c41d4b1a419ea40c3a38ce3adf1/R/dashboardNavbar.R#L70-L89

-> Would this be the place to have the color not hard coded?

**Comment by DivadNojnarg** [comment]
Actually when I started bs4Dash development, there was an issue in the CSS that obliged me to write this code. I should definitely give it another try now. Thanks for the suggestion. Can you open a new issue? Thanks

**Comment by federicomarini** [comment]
Sure. Done here: https://github.com/RinteRface/bs4Dash/issues/70
